// Seeding script to add 100 medicines to the database
// Run this once to populate the database

const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const Medicine = require('../models/Medicine');
const User = require('../models/User');
const connectDB = require('../config/db');

// Common Indian medicines data (100 medicines)
const medicines = [
  // ============ ANTIBIOTICS ============
  {
    name: 'Augmentin 625 Duo',
    genericName: 'Amoxicillin + Clavulanate Potassium',
    brand: 'GSK',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd',
    category: 'Antibiotic',
    composition: 'Amoxicillin 500mg + Clavulanate 125mg',
    dosageForm: 'Tablet',
    strength: '625mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'KD/29/2/96/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'AC 625', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White strip with blue GSK logo' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Azithromycin 500',
    genericName: 'Azithromycin',
    brand: 'Zithromax',
    manufacturer: 'Pfizer Ltd',
    category: 'Antibiotic',
    composition: 'Azithromycin 500mg',
    dosageForm: 'Tablet',
    strength: '500mg',
    packageSize: '3 tablets/strip',
    licenseNumber: 'ZK/28/1/95/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Capsule-shaped', imprint: 'ZITHRO 500', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Blue and white packaging' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Ciprofloxacin 500',
    genericName: 'Ciprofloxacin',
    brand: 'Ciproxin',
    manufacturer: 'Bayer Pharmaceuticals Pvt Ltd',
    category: 'Antibiotic',
    composition: 'Ciprofloxacin Hydrochloride 500mg',
    dosageForm: 'Tablet',
    strength: '500mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'BPR/27/3/94/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'CIP 500', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White strip with Bayer cross' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Cefixime 200',
    genericName: 'Cefixime',
    brand: 'Suprax',
    manufacturer: 'Sanofi India Ltd',
    category: 'Antibiotic',
    composition: 'Cefixime 200mg',
    dosageForm: 'Tablet',
    strength: '200mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SL/30/2/97/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Light pink', shape: 'Oval', imprint: 'SUP 200', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Pink and white strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Levofloxacin 500',
    genericName: 'Levofloxacin',
    brand: 'Levolet',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    category: 'Antibiotic',
    composition: 'Levofloxacin 500mg',
    dosageForm: 'Tablet',
    strength: '500mg',
    packageSize: '5 tablets/strip',
    licenseNumber: 'SP/26/4/93/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Light orange', shape: 'Oval', imprint: 'LVO 500', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Orange strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Amoxicillin 500',
    genericName: 'Amoxicillin',
    brand: 'Mox',
    manufacturer: 'Alkem Laboratories Ltd',
    category: 'Antibiotic',
    composition: 'Amoxicillin 500mg',
    dosageForm: 'Capsule',
    strength: '500mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'ALK/25/1/92/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'Red and white', shape: 'Capsule', imprint: 'AMOX 500', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Red and white capsules' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Doxycycline 100',
    genericName: 'Doxycycline',
    brand: 'Doxytet',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Antibiotic',
    composition: 'Doxycycline Hyclate 100mg',
    dosageForm: 'Capsule',
    strength: '100mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'ML/24/2/91/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow', shape: 'Capsule', imprint: 'DOXY 100', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Yellow capsules' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Metronidazole 400',
    genericName: 'Metronidazole',
    brand: 'Flagyl',
    manufacturer: 'Sanofi India Ltd',
    category: 'Antibiotic',
    composition: 'Metronidazole 400mg',
    dosageForm: 'Tablet',
    strength: '400mg',
    packageSize: '15 tablets/strip',
    licenseNumber: 'SL/23/3/90/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'FLG 400', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Ceftriaxone 1g',
    genericName: 'Ceftriaxone',
    brand: 'Monocef',
    manufacturer: 'Alkem Laboratories Ltd',
    category: 'Antibiotic',
    composition: 'Ceftriaxone Sodium 1g',
    dosageForm: 'Injection',
    strength: '1g',
    packageSize: '1 vial',
    licenseNumber: 'ALK/22/4/89/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White powder', shape: 'Lyophilized', specialMarking: 'Vial with purple cap' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White vial with label' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Cloxacillin 500',
    genericName: 'Cloxacillin',
    brand: 'Bonacillin',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Antibiotic',
    composition: 'Cloxacillin Sodium 500mg',
    dosageForm: 'Capsule',
    strength: '500mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'ML/21/1/88/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'Red and white', shape: 'Capsule', imprint: 'CLOX 500', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Red/white capsules' },
    isVerified: true,
    riskLevel: 'medium'
  },

  // ============ ANALGESICS/PAIN RELIEVERS ============
  {
    name: 'Crocin 500',
    genericName: 'Paracetamol',
    brand: 'GSK',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd',
    category: 'Analgesic',
    composition: 'Paracetamol 500mg',
    dosageForm: 'Tablet',
    strength: '500mg',
    packageSize: '15 tablets/strip',
    licenseNumber: 'KD/20/2/87/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'CROCIN 500', coating: 'Uncoated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Red and white strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Dolo 650',
    genericName: 'Paracetamol',
    brand: 'Micro Labs',
    manufacturer: 'Micro Labs Ltd',
    category: 'Analgesic',
    composition: 'Paracetamol 650mg',
    dosageForm: 'Tablet',
    strength: '650mg',
    packageSize: '15 tablets/strip',
    licenseNumber: 'ML/19/3/86/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'DOLO 650', coating: 'Uncoated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip with red text' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Combiflam',
    genericName: 'Ibuprofen + Paracetamol',
    brand: 'Sanofi',
    manufacturer: 'Sanofi India Ltd',
    category: 'Analgesic',
    composition: 'Ibuprofen 400mg + Paracetamol 325mg',
    dosageForm: 'Tablet',
    strength: '400mg/325mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SL/18/4/85/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Orange', shape: 'Oval', imprint: 'COMBIFLAM', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Orange strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Ibugesic Plus',
    genericName: 'Ibuprofen + Paracetamol',
    brand: 'Cipla',
    manufacturer: 'Cipla Ltd',
    category: 'Analgesic',
    composition: 'Ibuprofen 400mg + Paracetamol 325mg',
    dosageForm: 'Tablet',
    strength: '400mg/325mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'CPL/17/1/84/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'IBP PLUS', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Naproxen 500',
    genericName: 'Naproxen',
    brand: 'Alkem',
    manufacturer: 'Alkem Laboratories Ltd',
    category: 'Analgesic',
    composition: 'Naproxen 500mg',
    dosageForm: 'Tablet',
    strength: '500mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ALK/16/2/83/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'NAP 500', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Tramadol 50',
    genericName: 'Tramadol',
    brand: 'Contramal',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    category: 'Analgesic',
    composition: 'Tramadol Hydrochloride 50mg',
    dosageForm: 'Capsule',
    strength: '50mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'SP/15/3/82/MH',
    scheduleType: 'H1',
    physicalFeatures: { color: 'Red and white', shape: 'Capsule', imprint: 'TRAM 50', coating: 'N/A' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Red/white capsules' },
    isVerified: true,
    riskLevel: 'critical',
    isFlaggedAsFake: true,
    reportCount: 8
  },
  {
    name: 'Aspirin 75',
    genericName: 'Aspirin',
    brand: 'Disprin',
    manufacturer: 'Reckitt Benckiser',
    category: 'Analgesic',
    composition: 'Aspirin 75mg',
    dosageForm: 'Tablet',
    strength: '75mg',
    packageSize: '14 tablets/strip',
    licenseNumber: 'RB/14/4/81/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'DISPRIN', coating: 'Enteric coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Orange strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Nise Gel',
    genericName: 'Nimesulide',
    brand: 'Nise',
    manufacturer: 'Micro Labs Ltd',
    category: 'Analgesic',
    composition: 'Nimesulide 1% w/w',
    dosageForm: 'Gel',
    strength: '1%',
    packageSize: '30g tube',
    licenseNumber: 'ML/13/1/80/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Light yellow gel', specialMarking: 'Transparent tube' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Yellow tube with blue cap' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Sumo',
    genericName: 'Nimesulide',
    brand: 'Sumo',
    manufacturer: 'Alkem Laboratories Ltd',
    category: 'Analgesic',
    composition: 'Nimesulide 100mg',
    dosageForm: 'Tablet',
    strength: '100mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ALK/12/2/79/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'Light yellow', shape: 'Round', imprint: 'SUMO 100', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Yellow strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Surgicure Plus',
    genericName: 'Mefenamic Acid + Paracetamol',
    brand: 'Mankind',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Analgesic',
    composition: 'Mefenamic Acid 250mg + Paracetamol 325mg',
    dosageForm: 'Tablet',
    strength: '250mg/325mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ML/11/3/78/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'SURGICURE', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },

  // ============ ANTIDIABETIC ============
  {
    name: 'Glucophage 500',
    genericName: 'Metformin',
    brand: 'Merck',
    manufacturer: 'Merck Ltd',
    category: 'Antidiabetic',
    composition: 'Metformin Hydrochloride 500mg',
    dosageForm: 'Tablet',
    strength: '500mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ML/10/4/77/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'GLUCO 500', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White strip with orange' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Janumet 50/500',
    genericName: 'Sitagliptin + Metformin',
    brand: 'Janumet',
    manufacturer: 'MSD Pharmaceuticals Pvt Ltd',
    category: 'Antidiabetic',
    composition: 'Sitagliptin 50mg + Metformin 500mg',
    dosageForm: 'Tablet',
    strength: '50mg/500mg',
    packageSize: '14 tablets/strip',
    licenseNumber: 'MSD/9/1/76/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Light pink', shape: 'Capsule-shaped', imprint: '575', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Red and white packaging' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Glycomet 500',
    genericName: 'Metformin',
    brand: 'Glycomet',
    manufacturer: 'USV Pvt Ltd',
    category: 'Antidiabetic',
    composition: 'Metformin Hydrochloride 500mg',
    dosageForm: 'Tablet',
    strength: '500mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'USV/8/2/75/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'GM 500', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Glimepiride 1',
    genericName: 'Glimepiride',
    brand: 'Glimy',
    manufacturer: 'Abbott Healthcare Pvt Ltd',
    category: 'Antidiabetic',
    composition: 'Glimepiride 1mg',
    dosageForm: 'Tablet',
    strength: '1mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ABT/7/3/74/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'GLIM 1', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Voglibose 0.2',
    genericName: 'Voglibose',
    brand: 'Volix',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Antidiabetic',
    composition: 'Voglibose 0.2mg',
    dosageForm: 'Tablet',
    strength: '0.2mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ML/6/4/73/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'VOLIX 0.2', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Glipizide 5',
    genericName: 'Glipizide',
    brand: 'Glucotrol',
    manufacturer: 'Panacea Biotech',
    category: 'Antidiabetic',
    composition: 'Glipizide 5mg',
    dosageForm: 'Tablet',
    strength: '5mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'PNC/5/1/72/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'GLIP 5', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Pioglitazone 15',
    genericName: 'Pioglitazone',
    brand: 'Pioglit',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    category: 'Antidiabetic',
    composition: 'Pioglitazone 15mg',
    dosageForm: 'Tablet',
    strength: '15mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SP/4/2/71/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'PIO 15', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Jardiance 10',
    genericName: 'Empagliflozin',
    brand: 'Jardiance',
    manufacturer: 'Boehringer Ingelheim',
    category: 'Antidiabetic',
    composition: 'Empagliflozin 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'BI/3/3/70/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow', shape: 'Round', imprint: 'S 10', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Yellow strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Diamicron MR 30',
    genericName: 'Gliclazide',
    brand: 'Diamicron',
    manufacturer: 'Serdia Pharmaceuticals',
    category: 'Antidiabetic',
    composition: 'Gliclazide 30mg',
    dosageForm: 'Tablet',
    strength: '30mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SER/2/4/69/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'D30MR', coating: 'Modified release' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White strip with blue' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Galvus 50',
    genericName: 'Vildagliptin',
    brand: 'Galvus',
    manufacturer: 'Novartis India Ltd',
    category: 'Antidiabetic',
    composition: 'Vildagliptin 50mg',
    dosageForm: 'Tablet',
    strength: '50mg',
    packageSize: '14 tablets/strip',
    licenseNumber: 'NOV/1/1/68/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'GALVUS 50', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },

  // ============ ANTIHYPERTENSIVE ============
  {
    name: 'Amlodipine 5',
    genericName: 'Amlodipine',
    brand: 'Amlostin',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Antihypertensive',
    composition: 'Amlodipine Besylate 5mg',
    dosageForm: 'Tablet',
    strength: '5mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'MCL/30/2/67/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'AML 5', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Telma 40',
    genericName: 'Telmisartan',
    brand: 'Telma',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    category: 'Antihypertensive',
    composition: 'Telmisartan 40mg',
    dosageForm: 'Tablet',
    strength: '40mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'Glen/29/3/66/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'T 40', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Cardace 5',
    genericName: 'Ramipril',
    brand: 'Cardace',
    manufacturer: 'Sanofi India Ltd',
    category: 'Antihypertensive',
    composition: 'Ramipril 5mg',
    dosageForm: 'Capsule',
    strength: '5mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'SL/28/4/65/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow/White capsule', shape: 'Capsule', imprint: 'C 5', coating: 'N/A' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Blue and white packaging' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Losar 50',
    genericName: 'Losartan',
    brand: 'Losar',
    manufacturer: 'USV Pvt Ltd',
    category: 'Antihypertensive',
    composition: 'Losartan Potassium 50mg',
    dosageForm: 'Tablet',
    strength: '50mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'USV/27/1/64/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'L 50', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Metoprolol 50',
    genericName: 'Metoprolol',
    brand: 'Metolar',
    manufacturer: 'Cipla Ltd',
    category: 'Antihypertensive',
    composition: 'Metoprolol Tartrate 50mg',
    dosageForm: 'Tablet',
    strength: '50mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'CPL/26/2/63/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'MT 50', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Aten 50',
    genericName: 'Atenolol',
    brand: 'Aten',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Antihypertensive',
    composition: 'Atenolol 50mg',
    dosageForm: 'Tablet',
    strength: '50mg',
    packageSize: '14 tablets/strip',
    licenseNumber: 'ML/25/3/62/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'ATEN 50', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Olmezest 20',
    genericName: 'Olmesartan',
    brand: 'Olmezest',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Antihypertensive',
    composition: 'Olmesartan Medoxomil 20mg',
    dosageForm: 'Tablet',
    strength: '20mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'MCL/24/4/61/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'OLM 20', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Nebicip 5',
    genericName: 'Nebivolol',
    brand: 'Nebicip',
    manufacturer: 'Cipla Ltd',
    category: 'Antihypertensive',
    composition: 'Nebivolol 5mg',
    dosageForm: 'Tablet',
    strength: '5mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'CPL/23/1/60/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'NEB 5', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Exforge 5/80',
    genericName: 'Amlodipine + Valsartan',
    brand: 'Exforge',
    manufacturer: 'Novartis India Ltd',
    category: 'Antihypertensive',
    composition: 'Amlodipine 5mg + Valsartan 80mg',
    dosageForm: 'Tablet',
    strength: '5mg/80mg',
    packageSize: '7 tablets/strip',
    licenseNumber: 'NOV/22/2/59/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow', shape: 'Oval', imprint: 'NVR', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Yellow strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Razel 10',
    genericName: 'Rosuvastatin',
    brand: 'Razel',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    category: 'Antihypertensive',
    composition: 'Rosuvastatin 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'Glen/21/3/58/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Pink', shape: 'Round', imprint: 'RZ 10', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Pink strip' },
    isVerified: true,
    riskLevel: 'high'
  },

  // ============ RESPIRATORY ============
  {
    name: 'Asthalin Inhaler',
    genericName: 'Salbutamol',
    brand: 'Asthalin',
    manufacturer: 'Cipla Ltd',
    category: 'Respiratory',
    composition: 'Salbutamol 100mcg/actuation',
    dosageForm: 'Inhaler',
    strength: '100mcg',
    packageSize: '200 actuations',
    licenseNumber: 'CPL/20/4/57/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Blue inhaler', shape: 'Metered dose', specialMarking: 'Cipla logo, dose counter' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, securitySealPresent: true, colorDescription: 'Blue inhaler body' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Deriphyllin Retard 150',
    genericName: 'Theophylline + Etophylline',
    brand: 'Deriphyllin',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Respiratory',
    composition: 'Theophylline 150mg + Etophylline 100mg',
    dosageForm: 'Tablet',
    strength: '150mg/100mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'MCL/19/1/56/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'DERI 150', coating: 'Extended release' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Montair 10',
    genericName: 'Montelukast',
    brand: 'Montair',
    manufacturer: 'Cipla Ltd',
    category: 'Respiratory',
    composition: 'Montelukast 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'CPL/18/2/55/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Beige', shape: 'Round', imprint: 'MONT 10', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Beige strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Budecort 200',
    genericName: 'Budesonide',
    brand: 'Budecort',
    manufacturer: 'Cipla Ltd',
    category: 'Respiratory',
    composition: 'Budesonide 200mcg/actuation',
    dosageForm: 'Inhaler',
    strength: '200mcg',
    packageSize: '200 doses',
    licenseNumber: 'CPL/17/3/54/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Brown inhaler', shape: 'Rotahaler', specialMarking: 'Brown body' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Brown inhaler' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Duolin Inhaler',
    genericName: 'Salbutamol + Ipratropium',
    brand: 'Duolin',
    manufacturer: 'Cipla Ltd',
    category: 'Respiratory',
    composition: 'Salbutamol 50mcg + Ipratropium 20mcg',
    dosageForm: 'Inhaler',
    strength: '50mcg/20mcg',
    packageSize: '200 actuations',
    licenseNumber: 'CPL/16/4/53/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow/Blue', shape: 'Inhaler', specialMarking: 'Dual color' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Yellow and blue' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Tiova Inhaler',
    genericName: 'Tiotropium',
    brand: 'Tiova',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    category: 'Respiratory',
    composition: 'Tiotropium 18mcg',
    dosageForm: 'Inhaler',
    strength: '18mcg',
    packageSize: '30 capsules + 1 inhaler',
    licenseNumber: 'SP/15/1/52/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Green inhaler', shape: 'Capsule', specialMarking: 'Green body' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Green inhaler' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Asonor Nasal Spray',
    genericName: 'Sodium Chloride',
    brand: 'Asonor',
    manufacturer: 'Cipla Ltd',
    category: 'Respiratory',
    composition: 'Sodium Chloride 0.65%',
    dosageForm: 'Drops',
    strength: '0.65%',
    packageSize: '15ml',
    licenseNumber: 'CPL/14/2/51/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Clear liquid', specialMarking: 'Dropper bottle' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White bottle' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Mucolytic Expectorant',
    genericName: 'Ambroxol',
    brand: 'Ambroxol',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Respiratory',
    composition: 'Ambroxol Hydrochloride 30mg/5ml',
    dosageForm: 'Syrup',
    strength: '30mg/5ml',
    packageSize: '100ml',
    licenseNumber: 'ML/13/3/50/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Clear syrup', specialMarking: 'Strawberry flavor' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Amber bottle' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Koflet Syrup',
    genericName: 'Herbal Cough Syrup',
    brand: 'Koflet',
    manufacturer: 'Himalaya Drug Company',
    category: 'Respiratory',
    composition: 'Herbal blend with Vishwa, Licorice',
    dosageForm: 'Syrup',
    strength: 'N/A',
    packageSize: '100ml',
    licenseNumber: 'HIM/12/4/49/BL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Brown syrup', specialMarking: 'Herbal' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Brown bottle' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Cetirizine 10',
    genericName: 'Cetirizine',
    brand: 'Cetzine',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    category: 'Antihistamine',
    composition: 'Cetirizine Hydrochloride 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'Glen/11/1/48/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'CET 10', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'low'
  },

  // ============ ANTIHISTAMINES ============
  {
    name: 'Allegra 180',
    genericName: 'Fexofenadine',
    brand: 'Allegra',
    manufacturer: 'Sanofi India Ltd',
    category: 'Antihistamine',
    composition: 'Fexofenadine Hydrochloride 180mg',
    dosageForm: 'Tablet',
    strength: '180mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SL/10/2/47/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Peach/Orange', shape: 'Oval', imprint: '018', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Orange and white strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Levocetirizine 5',
    genericName: 'Levocetirizine',
    brand: 'Lezync',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Antihistamine',
    composition: 'Levocetirizine Dihydrochloride 5mg',
    dosageForm: 'Tablet',
    strength: '5mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ML/9/3/46/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'LEV 5', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Avil 25',
    genericName: 'Pheniramine',
    brand: 'Avil',
    manufacturer: 'Sanofi India Ltd',
    category: 'Antihistamine',
    composition: 'Pheniramine Maleate 25mg',
    dosageForm: 'Tablet',
    strength: '25mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SL/8/4/45/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'AVIL 25', coating: 'Uncoated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Reactin 10',
    genericName: 'Cetirizine',
    brand: 'Reactin',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    category: 'Antihistamine',
    composition: 'Cetirizine Hydrochloride 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SP/7/1/44/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'RCT 10', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Desloratadine 5',
    genericName: 'Desloratadine',
    brand: 'Deslor',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Antihistamine',
    composition: 'Desloratadine 5mg',
    dosageForm: 'Tablet',
    strength: '5mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'MCL/6/2/43/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Light blue', shape: 'Round', imprint: 'DES 5', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Blue strip' },
    isVerified: true,
    riskLevel: 'low'
  },

  // ============ ANTACIDS & GASTROINTESTINAL ============
  {
    name: 'Omeprazole 20',
    genericName: 'Omeprazole',
    brand: 'Omez',
    manufacturer: 'Dr. Reddy\'s Laboratories Ltd',
    category: 'Antacid',
    composition: 'Omeprazole 20mg',
    dosageForm: 'Capsule',
    strength: '20mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'DRL/5/3/42/TS',
    scheduleType: 'H',
    physicalFeatures: { color: 'Purple and white', shape: 'Capsule', imprint: 'OME 20', coating: 'Enteric coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Purple/white capsules' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Pantocid 40',
    genericName: 'Pantoprazole',
    brand: 'Pantocid',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Antacid',
    composition: 'Pantoprazole 40mg',
    dosageForm: 'Tablet',
    strength: '40mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'MCL/4/4/41/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow', shape: 'Oval', imprint: 'P40', coating: 'Enteric coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Yellow strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Rabeprazole 20',
    genericName: 'Rabeprazole',
    brand: 'Razole',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Antacid',
    composition: 'Rabeprazole 20mg',
    dosageForm: 'Tablet',
    strength: '20mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ML/3/1/40/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'Pink', shape: 'Round', imprint: 'RAZ 20', coating: 'Enteric coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Pink strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Rantac 150',
    genericName: 'Ranitidine',
    brand: 'Rantac',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Antacid',
    composition: 'Ranitidine Hydrochloride 150mg',
    dosageForm: 'Tablet',
    strength: '150mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'MCL/2/2/39/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'RAN 150', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Domstal 10',
    genericName: 'Domperidone',
    brand: 'Domstal',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Antacid',
    composition: 'Domperidone 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'MCL/1/3/38/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'DOM 10', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'ENO Regular',
    genericName: 'Sodium Bicarbonate + Citric Acid',
    brand: 'ENO',
    manufacturer: 'GlaxoSmithKline Consumer Healthcare',
    category: 'Antacid',
    composition: 'Sodium Bicarbonate 2.32g + Citric Acid 2.18g',
    dosageForm: 'Other',
    strength: '5g/sachet',
    packageSize: '30 sachets/pack',
    licenseNumber: 'KD/30/4/37/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White powder', specialMarking: 'Orange granules visible' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Orange sachet' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Gelusil',
    genericName: 'Aluminum Hydroxide + Magnesium Hydroxide',
    brand: 'Gelusil',
    manufacturer: 'Pfizer Ltd',
    category: 'Antacid',
    composition: 'Aluminum Hydroxide 250mg + Magnesium Hydroxide 250mg',
    dosageForm: 'Chewable Tablet',
    strength: '250mg/250mg',
    packageSize: '15 tablets/box',
    licenseNumber: 'PFL/29/1/36/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Pink', shape: 'Round', imprint: 'GELUSIL', coating: 'Chewable' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Pink tablets' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Digene Gel',
    genericName: 'Magaldrate + Simethicone',
    brand: 'Digene',
    manufacturer: 'Abbott Healthcare Pvt Ltd',
    category: 'Antacid',
    composition: 'Magaldrate 400mg + Simethicone 20mg',
    dosageForm: 'Chewable Tablet',
    strength: '400mg/20mg',
    packageSize: '15 tablets/box',
    licenseNumber: 'ABT/28/2/35/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'DIGENE', coating: 'Chewable' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White tablets' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Ondansetron 4',
    genericName: 'Ondansetron',
    brand: 'Emeset',
    manufacturer: 'Cipla Ltd',
    category: 'Antacid',
    composition: 'Ondansetron 4mg',
    dosageForm: 'Tablet',
    strength: '4mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'CPL/27/3/34/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'EMESET 4', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Pantoprazole 40',
    genericName: 'Pantoprazole',
    brand: 'Pan',
    manufacturer: 'Alkem Laboratories Ltd',
    category: 'Antacid',
    composition: 'Pantoprazole 40mg',
    dosageForm: 'Injection',
    strength: '40mg',
    packageSize: '1 vial',
    licenseNumber: 'ALK/26/4/33/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White powder', shape: 'Lyophilized', specialMarking: 'Vial' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White vial' },
    isVerified: true,
    riskLevel: 'high'
  },

  // ============ CARDIOVASCULAR ============
  {
    name: 'Ecosprin 75',
    genericName: 'Aspirin',
    brand: 'Ecosprin',
    manufacturer: 'USV Pvt Ltd',
    category: 'Cardiovascular',
    composition: 'Aspirin 75mg',
    dosageForm: 'Tablet',
    strength: '75mg',
    packageSize: '14 tablets/strip',
    licenseNumber: 'USV/25/1/32/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', coating: 'Enteric coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Atorvastatin 10',
    genericName: 'Atorvastatin',
    brand: 'Atorva',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    category: 'Cardiovascular',
    composition: 'Atorvastatin 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'Glen/24/2/31/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'ATV 10', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Rosuvastatin 10',
    genericName: 'Rosuvastatin',
    brand: 'Rosukem',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Cardiovascular',
    composition: 'Rosuvastatin 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'MCL/23/3/30/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Pink', shape: 'Round', imprint: 'RSK 10', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Pink strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Clopidogrel 75',
    genericName: 'Clopidogrel',
    brand: 'Plavix',
    manufacturer: 'Sanofi India Ltd',
    category: 'Cardiovascular',
    composition: 'Clopidogrel Hydrogen Sulphate 75mg',
    dosageForm: 'Tablet',
    strength: '75mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SL/22/4/29/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Pink', shape: 'Round', imprint: '75', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Pink strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Isosorbide Mononitrate 20',
    genericName: 'Isosorbide Mononitrate',
    brand: 'Monotrate',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    category: 'Cardiovascular',
    composition: 'Isosorbide Mononitrate 20mg',
    dosageForm: 'Tablet',
    strength: '20mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SP/21/1/28/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'MONO 20', coating: 'Extended release' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Carvedilol 6.25',
    genericName: 'Carvedilol',
    brand: 'Carvas',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Cardiovascular',
    composition: 'Carvedilol 6.25mg',
    dosageForm: 'Tablet',
    strength: '6.25mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ML/20/2/27/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'CV 6.25', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Furosemide 40',
    genericName: 'Furosemide',
    brand: 'Lasix',
    manufacturer: 'Sanofi India Ltd',
    category: 'Cardiovascular',
    composition: 'Furosemide 40mg',
    dosageForm: 'Tablet',
    strength: '40mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SL/19/3/26/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'LASIX', coating: 'Uncoated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Spironolactone 25',
    genericName: 'Spironolactone',
    brand: 'Aldactone',
    manufacturer: 'Pfizer Ltd',
    category: 'Cardiovascular',
    composition: 'Spironolactone 25mg',
    dosageForm: 'Tablet',
    strength: '25mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'PFL/18/4/25/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow', shape: 'Round', imprint: 'ALDO 25', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Yellow strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Digoxin 0.25',
    genericName: 'Digoxin',
    brand: 'Lanoxin',
    manufacturer: 'Pfizer Ltd',
    category: 'Cardiovascular',
    composition: 'Digoxin 0.25mg',
    dosageForm: 'Tablet',
    strength: '0.25mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'PFL/17/1/24/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'LX 0.25', coating: 'Uncoated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'critical'
  },
  {
    name: 'Amlodipine 5',
    genericName: 'Amlodipine',
    brand: 'Amlodep',
    manufacturer: 'Micro Labs Ltd',
    category: 'Antihypertensive',
    composition: 'Amlodipine Besylate 5mg',
    dosageForm: 'Tablet',
    strength: '5mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ML/16/2/23/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'AMLP 5', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'medium',
    isFlaggedAsFake: true,
    reportCount: 5
  },

  // ============ NEUROLOGICAL ============
  {
    name: 'Pregabalin 75',
    genericName: 'Pregabalin',
    brand: 'Pregalin',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    category: 'Neurological',
    composition: 'Pregabalin 75mg',
    dosageForm: 'Capsule',
    strength: '75mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'SP/15/3/22/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Light brown', shape: 'Capsule', imprint: 'PGB 75', coating: 'N/A' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Brown/white capsules' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Gabapentin 300',
    genericName: 'Gabapentin',
    brand: 'Gabapin',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Neurological',
    composition: 'Gabapentin 300mg',
    dosageForm: 'Capsule',
    strength: '300mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'ML/14/4/21/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow', shape: 'Capsule', imprint: 'GAB 300', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Yellow capsules' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Escitalopram 10',
    genericName: 'Escitalopram',
    brand: 'Citalin',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Neurological',
    composition: 'Escitalopram 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'MCL/13/1/20/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'CIT 10', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Sertraline 50',
    genericName: 'Sertraline',
    brand: 'Serlift',
    manufacturer: 'Cipla Ltd',
    category: 'Neurological',
    composition: 'Sertraline Hydrochloride 50mg',
    dosageForm: 'Tablet',
    strength: '50mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'CPL/12/2/19/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Blue', shape: 'Oval', imprint: 'SRT 50', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Blue strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Fluoxetine 20',
    genericName: 'Fluoxetine',
    brand: 'Fludac',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Neurological',
    composition: 'Fluoxetine Hydrochloride 20mg',
    dosageForm: 'Capsule',
    strength: '20mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'MCL/11/3/18/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Green and white', shape: 'Capsule', imprint: 'FLU 20', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Green/white capsules' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Duloxetine 20',
    genericName: 'Duloxetine',
    brand: 'Duzylo',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Neurological',
    composition: 'Duloxetine 20mg',
    dosageForm: 'Capsule',
    strength: '20mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'MCL/10/4/17/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Blue', shape: 'Capsule', imprint: 'DUL 20', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Blue capsules' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Sodium Valproate 200',
    genericName: 'Sodium Valproate',
    brand: 'Valtec',
    manufacturer: 'Alkem Laboratories Ltd',
    category: 'Neurological',
    composition: 'Sodium Valproate 200mg',
    dosageForm: 'Tablet',
    strength: '200mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ALK/9/1/16/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'VAL 200', coating: 'Enteric coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Phenytoin 100',
    genericName: 'Phenytoin',
    brand: 'Eptoin',
    manufacturer: 'Abbott Healthcare Pvt Ltd',
    category: 'Neurological',
    composition: 'Phenytoin Sodium 100mg',
    dosageForm: 'Tablet',
    strength: '100mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ABT/8/2/15/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'EPTOIN', coating: 'Enteric coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'critical',
    isFlaggedAsFake: true,
    reportCount: 6
  },
  {
    name: 'Levocetirizine 5',
    genericName: 'Levocetirizine',
    brand: 'L-Cet',
    manufacturer: 'Micro Labs Ltd',
    category: 'Antihistamine',
    composition: 'Levocetirizine Dihydrochloride 5mg',
    dosageForm: 'Tablet',
    strength: '5mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ML/7/3/14/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'LCET 5', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Alprazolam 0.5',
    genericName: 'Alprazolam',
    brand: 'Alprax',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    category: 'Neurological',
    composition: 'Alprazolam 0.5mg',
    dosageForm: 'Tablet',
    strength: '0.5mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SP/6/4/13/MH',
    scheduleType: 'H1',
    physicalFeatures: { color: 'White', shape: 'Oval', imprint: 'ALP 0.5', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'critical'
  },

  // ============ VITAMINS/SUPPLEMENTS ============
  {
    name: 'Shelcal 500',
    genericName: 'Calcium',
    brand: 'Shelcal',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Vitamin/Supplement',
    composition: 'Calcium Carbonate 500mg + Vitamin D3 250IU',
    dosageForm: 'Tablet',
    strength: '500mg/250IU',
    packageSize: '15 tablets/jar',
    licenseNumber: 'ML/5/1/12/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'SHELCAL', coating: 'Chewable' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White jar' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Supradyn',
    genericName: 'Multivitamin',
    brand: 'Supradyn',
    manufacturer: 'Bayer Pharmaceuticals',
    category: 'Vitamin/Supplement',
    composition: 'Multivitamin + Minerals',
    dosageForm: 'Tablet',
    strength: 'N/A',
    packageSize: '15 tablets/box',
    licenseNumber: 'BPR/4/2/11/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Orange', shape: 'Oval', imprint: 'SUPRADYN', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Orange strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Neurobion Forte',
    genericName: 'Vitamin B Complex',
    brand: 'Neurobion',
    manufacturer: 'Merck Ltd',
    category: 'Vitamin/Supplement',
    composition: 'Vitamin B1 10mg + B6 3mg + B12 15mcg',
    dosageForm: 'Tablet',
    strength: '10mg/3mg/15mcg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'ML/3/3/10/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Red', shape: 'Oval', imprint: 'NEUROBION', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Red strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Becosules',
    genericName: 'Vitamin B Complex',
    brand: 'Becosules',
    manufacturer: 'Cipla Ltd',
    category: 'Vitamin/Supplement',
    composition: 'Vitamin B Complex',
    dosageForm: 'Capsule',
    strength: 'N/A',
    packageSize: '10 capsules/strip',
    licenseNumber: 'CPL/2/4/09/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Red', shape: 'Capsule', imprint: 'BEC', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Red capsules' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Folvite 5mg',
    genericName: 'Folic Acid',
    brand: 'Folvite',
    manufacturer: 'Sun Pharmaceutical Industries Ltd',
    category: 'Vitamin/Supplement',
    composition: 'Folic Acid 5mg',
    dosageForm: 'Tablet',
    strength: '5mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'SP/1/1/08/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Yellow', shape: 'Round', imprint: 'FOLVITE', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Yellow strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Iron Complex',
    genericName: 'Iron',
    brand: 'Fefol',
    manufacturer: 'GSK',
    category: 'Vitamin/Supplement',
    composition: 'Ferrous Sulphate 150mg + Folic Acid 0.5mg',
    dosageForm: 'Capsule',
    strength: '150mg/0.5mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'KD/30/2/07/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Red and white', shape: 'Capsule', imprint: 'FEFOL', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Red/white capsules' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Zinc Gluconate',
    genericName: 'Zinc',
    brand: 'Zincovit',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    category: 'Vitamin/Supplement',
    composition: 'Zinc Gluconate 20mg',
    dosageForm: 'Tablet',
    strength: '20mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'Glen/29/3/06/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'ZINC 20', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Vitamin D3 60K',
    genericName: 'Cholecalciferol',
    brand: 'D3',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Vitamin/Supplement',
    composition: 'Cholecalciferol 60000IU',
    dosageForm: 'Capsule',
    strength: '60000IU',
    packageSize: '4 capsules/strip',
    licenseNumber: 'ML/28/4/05/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Yellow', shape: 'Capsule', imprint: 'D3 60K', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Yellow capsules' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Becadexamin',
    genericName: 'Multivitamin',
    brand: 'Becadexamin',
    manufacturer: 'Fdc Ltd',
    category: 'Vitamin/Supplement',
    composition: 'Multivitamin + Minerals',
    dosageForm: 'Tablet',
    strength: 'N/A',
    packageSize: '15 tablets/jar',
    licenseNumber: 'FDC/27/1/04/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Orange', shape: 'Round', imprint: 'BECA', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Orange jar' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Lysine Syrup',
    genericName: 'Lysine',
    brand: 'Lysovit',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Vitamin/Supplement',
    composition: 'Lysine 375mg/5ml',
    dosageForm: 'Syrup',
    strength: '375mg/5ml',
    packageSize: '200ml',
    licenseNumber: 'ML/26/2/03/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Pink syrup', specialMarking: 'Strawberry flavor' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Pink bottle' },
    isVerified: true,
    riskLevel: 'low'
  },

  // ============ ANTIFUNGAL ============
  {
    name: 'Fluconazole 150',
    genericName: 'Fluconazole',
    brand: 'Flucan',
    manufacturer: 'Macleods Pharmaceuticals Ltd',
    category: 'Antifungal',
    composition: 'Fluconazole 150mg',
    dosageForm: 'Capsule',
    strength: '150mg',
    packageSize: '1 capsule/blister',
    licenseNumber: 'MCL/25/3/02/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Blue and white', shape: 'Capsule', imprint: 'FLU 150', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Blue/white capsule' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Clotrimazole Cream',
    genericName: 'Clotrimazole',
    brand: 'Candid',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    category: 'Antifungal',
    composition: 'Clotrimazole 1% w/w',
    dosageForm: 'Cream',
    strength: '1%',
    packageSize: '15g tube',
    licenseNumber: 'Glen/24/4/01/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White cream', specialMarking: 'Tube' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White tube' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Itraconazole 100',
    genericName: 'Itraconazole',
    brand: 'Canditral',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    category: 'Antifungal',
    composition: 'Itraconazole 100mg',
    dosageForm: 'Capsule',
    strength: '100mg',
    packageSize: '4 capsules/strip',
    licenseNumber: 'Glen/23/1/00/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White and red', shape: 'Capsule', imprint: 'ITR 100', coating: 'N/A' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White/red capsules' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Terbinafine 250',
    genericName: 'Terbinafine',
    brand: 'Terbicip',
    manufacturer: 'Cipla Ltd',
    category: 'Antifungal',
    composition: 'Terbinafine Hydrochloride 250mg',
    dosageForm: 'Tablet',
    strength: '250mg',
    packageSize: '7 tablets/strip',
    licenseNumber: 'CPL/22/2/99/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'White', shape: 'Round', imprint: 'TBF 250', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White strip' },
    isVerified: true,
    riskLevel: 'high'
  },
  {
    name: 'Nystatin Suspension',
    genericName: 'Nystatin',
    brand: 'Nystatin',
    manufacturer: 'Panacea Biotech',
    category: 'Antifungal',
    composition: 'Nystatin 100000IU/ml',
    dosageForm: 'Syrup',
    strength: '100000IU/ml',
    packageSize: '30ml',
    licenseNumber: 'PNC/21/3/98/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Yellow suspension', specialMarking: 'Suspension' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Amber bottle' },
    isVerified: true,
    riskLevel: 'low'
  },

  // ============ ANTIVIRAL ============
  {
    name: 'Acyclovir 400',
    genericName: 'Acyclovir',
    brand: 'Zovirax',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd',
    category: 'Antiviral',
    composition: 'Acyclovir 400mg',
    dosageForm: 'Tablet',
    strength: '400mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'KD/20/4/97/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'Blue', shape: 'Capsule-shaped', imprint: 'ZOVIRAX', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Blue strip' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Oseltamivir 75',
    genericName: 'Oseltamivir',
    brand: 'Tamiflu',
    manufacturer: 'Roche',
    category: 'Antiviral',
    composition: 'Oseltamivir Phosphate 75mg',
    dosageForm: 'Capsule',
    strength: '75mg',
    packageSize: '10 capsules/strip',
    licenseNumber: 'RCH/19/1/96/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow and white', shape: 'Capsule', imprint: '75mg', coating: 'N/A' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Yellow/white capsules' },
    isVerified: true,
    riskLevel: 'high'
  },

  // ============ OTHER COMMON MEDICINES ============
  {
    name: 'Betnovate-C Cream',
    genericName: 'Betamethasone + Clioquinol',
    brand: 'Betnovate',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd',
    category: 'Other',
    composition: 'Betamethasone Valerate 0.1% + Clioquinol 3%',
    dosageForm: 'Cream',
    strength: '0.1%/3%',
    packageSize: '20g tube',
    licenseNumber: 'KD/18/2/95/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White cream', coating: 'N/A', specialMarking: 'GSK logo on tube' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'White tube with orange/red label' },
    isVerified: true,
    riskLevel: 'critical',
    isFlaggedAsFake: true,
    reportCount: 8
  },
  {
    name: 'Tetracycline Eye Ointment',
    genericName: 'Tetracycline',
    brand: 'Tetracin',
    manufacturer: 'Cipla Ltd',
    category: 'Other',
    composition: 'Tetracycline 1%',
    dosageForm: 'Ointment',
    strength: '1%',
    packageSize: '3.5g tube',
    licenseNumber: 'CPL/17/3/94/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Yellow ointment', specialMarking: 'Tube' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Yellow tube' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Hydrocortisone Cream 1%',
    genericName: 'Hydrocortisone',
    brand: 'Hydrozole',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Other',
    composition: 'Hydrocortisone 1% w/w',
    dosageForm: 'Cream',
    strength: '1%',
    packageSize: '15g tube',
    licenseNumber: 'ML/16/4/93/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White cream', specialMarking: 'Tube' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White tube' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Mupirocin Ointment',
    genericName: 'Mupirocin',
    brand: 'T-Bact',
    manufacturer: 'Glenmark Pharmaceuticals Ltd',
    category: 'Other',
    composition: 'Mupirocin 2% w/w',
    dosageForm: 'Ointment',
    strength: '2%',
    packageSize: '5g tube',
    licenseNumber: 'Glen/15/1/92/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White ointment', specialMarking: 'Tube' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White tube' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Povidone Iodine',
    genericName: 'Povidone Iodine',
    brand: 'Betadine',
    manufacturer: 'Sanofi India Ltd',
    category: 'Other',
    composition: 'Povidone Iodine 5% w/v',
    dosageForm: 'Solution',
    strength: '5%',
    packageSize: '100ml',
    licenseNumber: 'SL/14/2/91/MH',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Brown liquid', specialMarking: 'Liquid' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Brown bottle' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'ORS Packet',
    genericName: 'Oral Rehydration Salt',
    brand: 'Electral',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Other',
    composition: 'ORS Formula',
    dosageForm: 'Other',
    strength: '20.5g/packet',
    packageSize: '1 packet',
    licenseNumber: 'ML/13/3/90/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White powder', specialMarking: 'Sachet' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White packet' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Antacid Syrup',
    genericName: 'Magaldrate + Simethicone',
    brand: 'Digene',
    manufacturer: 'Abbott Healthcare Pvt Ltd',
    category: 'Antacid',
    composition: 'Magaldrate 400mg + Simethicone 20mg per 5ml',
    dosageForm: 'Syrup',
    strength: '400mg/20mg per 5ml',
    packageSize: '200ml',
    licenseNumber: 'ABT/12/4/89/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Cream suspension', specialMarking: 'Suspension' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Amber bottle' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Cetrizine M Syrup',
    genericName: 'Cetirizine + Pseudoephedrine',
    brand: 'Cetrizine M',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Antihistamine',
    composition: 'Cetirizine 5mg + Pseudoephedrine 30mg per 5ml',
    dosageForm: 'Syrup',
    strength: '5mg/30mg per 5ml',
    packageSize: '60ml',
    licenseNumber: 'ML/11/1/88/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Colorless syrup', specialMarking: 'Strawberry flavor' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White bottle' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Amoxicillin Syrup',
    genericName: 'Amoxicillin',
    brand: 'Mox',
    manufacturer: 'Alkem Laboratories Ltd',
    category: 'Antibiotic',
    composition: 'Amoxicillin 250mg per 5ml',
    dosageForm: 'Syrup',
    strength: '250mg per 5ml',
    packageSize: '60ml',
    licenseNumber: 'ALK/10/2/87/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow suspension', specialMarking: 'Strawberry flavor' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Amber bottle' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Azithromycin Syrup',
    genericName: 'Azithromycin',
    brand: 'Azithral',
    manufacturer: 'Alkem Laboratories Ltd',
    category: 'Antibiotic',
    composition: 'Azithromycin 200mg per 5ml',
    dosageForm: 'Syrup',
    strength: '200mg per 5ml',
    packageSize: '30ml',
    licenseNumber: 'ALK/9/3/86/DL',
    scheduleType: 'H',
    physicalFeatures: { color: 'White suspension', specialMarking: 'Cherry flavor' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White bottle' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Cough Expectorant',
    genericName: 'Ambroxol + Levosalbutamol',
    brand: 'Asthalin Expectorant',
    manufacturer: 'Cipla Ltd',
    category: 'Respiratory',
    composition: 'Ambroxol 30mg + Levosalbutamol 1mg per 5ml',
    dosageForm: 'Syrup',
    strength: '30mg/1mg per 5ml',
    packageSize: '100ml',
    licenseNumber: 'CPL/8/4/85/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Clear syrup', specialMarking: 'Mixed fruit flavor' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Blue bottle' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Liver Tonic',
    genericName: 'Silymarin + Vitamins',
    brand: 'Liv 52',
    manufacturer: 'Himalaya Drug Company',
    category: 'Other',
    composition: 'Silymarin + Vitamins',
    dosageForm: 'Syrup',
    strength: 'N/A',
    packageSize: '200ml',
    licenseNumber: 'HIM/7/1/84/BL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'Brown syrup', specialMarking: 'Herbal' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Brown bottle' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Polycrol',
    genericName: 'Dimethicone + Magnesium Hydroxide',
    brand: 'Polycrol',
    manufacturer: 'Mankind Pharma Ltd',
    category: 'Antacid',
    composition: 'Dimethicone 40mg + Magnesium Hydroxide 300mg per 5ml',
    dosageForm: 'Syrup',
    strength: '40mg/300mg per 5ml',
    packageSize: '100ml',
    licenseNumber: 'ML/6/2/83/DL',
    scheduleType: 'OTC',
    physicalFeatures: { color: 'White suspension', specialMarking: 'Mint flavor' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'White bottle' },
    isVerified: true,
    riskLevel: 'low'
  },
  {
    name: 'Metronidazole Syrup',
    genericName: 'Metronidazole',
    brand: 'Flagyl',
    manufacturer: 'Sanofi India Ltd',
    category: 'Antibiotic',
    composition: 'Metronidazole 200mg per 5ml',
    dosageForm: 'Syrup',
    strength: '200mg per 5ml',
    packageSize: '60ml',
    licenseNumber: 'SL/5/3/82/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Pink suspension', specialMarking: 'Vanilla flavor' },
    packagingFeatures: { hologramPresent: false, barcodePresent: true, colorDescription: 'Amber bottle' },
    isVerified: true,
    riskLevel: 'medium'
  },
  {
    name: 'Norethisterone 5mg',
    genericName: 'Norethisterone',
    brand: 'Primolut N',
    manufacturer: 'Bayer Pharmaceuticals',
    category: 'Contraceptive',
    composition: 'Norethisterone 5mg',
    dosageForm: 'Tablet',
    strength: '5mg',
    packageSize: '10 tablets/strip',
    licenseNumber: 'BPR/4/4/81/MH',
    scheduleType: 'H',
    physicalFeatures: { color: 'Yellow', shape: 'Round', imprint: 'PRIMOLUT', coating: 'Film coated' },
    packagingFeatures: { hologramPresent: true, barcodePresent: true, colorDescription: 'Yellow strip' },
    isVerified: true,
    riskLevel: 'high'
  }
];

const seedDB = async () => {
  try {
    await connectDB();
    
    // Clear existing medicines
    await Medicine.deleteMany({});
    console.log('🗑️  Cleared existing medicines');

    // Insert seed data
    const inserted = await Medicine.insertMany(medicines);
    console.log(`✅ Seeded ${inserted.length} medicines`);

    // Create admin user if doesn't exist
    const adminExists = await User.findOne({ email: 'admin@medverify.in' });
    if (!adminExists) {
      await User.create({
        name: 'MedVerify Admin',
        email: 'admin@medverify.in',
        password: 'Admin@MedVerify2024',
        role: 'admin',
        isEmailVerified: true,
        state: 'Delhi',
        city: 'New Delhi'
      });
      console.log('✅ Admin user created: admin@medverify.in / Admin@MedVerify2024');
    }

    console.log('🌱 Database seeded successfully!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err);
    process.exit(1);
  }
};

// Export for use in other files
module.exports = { medicines, seedDB };

// Run if called directly
if (require.main === module) {
  seedDB();
}